# Generated by Django 5.1.7 on 2025-03-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='osm_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
