# Generated by Django 5.1.7 on 2025-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_image_url_restaurant_osm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
